<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SearchService.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SearchService.Domain\SearchService.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Common\Shared.Common.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.EventContracts\Shared.EventContracts.csproj" />
  </ItemGroup>
</Project>
